from enum import StrEnum

class CatClasses(StrEnum):
    abyssinian = 'Abyssinian'
    bengal = 'Bengal'
    birman  = 'Birman'
    bombay = 'Bombay'
    british_shorthair = 'British_Shorthair'
    egyptian_mau = 'Egyptian_Mau'
    maine_coon = 'Maine_Coon'
    persian = 'Persian'
    ragdoll = 'Ragdoll'
    russian_blue  = 'Russian_Blue'
    siamese = 'Siamese'
    sphynx = 'Sphynx'


class DogClasses(StrEnum):
    american_bulldog = 'american_bulldog'
    american_pit_bull_terrier = 'american_pit_bull_terrier'
    basset_hound = 'basset_hound'
    beagle = 'beagle'
    boxer = 'boxer'
    chihuahua = 'chihuahua'
    english_cocker_spaniel = 'english_cocker_spaniel'
    english_setter = 'english_setter'
    german_shorthaired = 'german_shorthaired'
    great_pyrenees = 'great_pyrenees'
    havanese = 'havanese'
    japanese_chin = 'japanese_chin'
    keeshond = 'keeshond'
    leonberger = 'leonberger'
    miniature_pinscher = 'miniature_pinscher'
    newfoundland = 'newfoundland'
    pomeranian = 'pomeranian'
    pug = 'pug'
    saint_bernard = 'saint_bernard'
    samoyed = 'samoyed'
    scottish_terrier = 'scottish_terrier'
    shiba_inu = 'shiba_inu'
    staffordshire_bull_terrier = 'staffordshire_bull_terrier'
    wheaten_terrier = 'wheaten_terrier'
    yorkshire_terrier = 'yorkshire_terrier'
